In [4]:
#Introduction to Numpy

In [10]:
# zero dim 
import numpy as np
arr = np.array(42)
print(arr)

42


In [8]:
# 1-D Array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

[1 2 3 4 5 6 7 8 9]


In [5]:
type(arr)

numpy.ndarray

In [11]:
# 2-D Array 
import numpy as np 
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
# 3-D Array 
import numpy as np 
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [14]:
# Checking no. of Dimensions in Arrays 
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
import numpy as np 

arr = np.array([1], ndmin=5)

print(arr)
print('number of dimensions', arr.ndim)

[[[[[1]]]]]
number of dimensions 5


In [19]:
# Getting the first element from the Array 
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [20]:
# Getting the second element from the Array 
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [21]:
# Getting the third and the fourth element from the Array 
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [22]:
#Accessing 2-D Arrays 

In [23]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

In [25]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [26]:
#Accessing 3-D Array 

In [27]:
# Create an array which contains numbers from 1 to 20 but prints only odd numbers 

In [30]:
import numpy as np
numbers = range(1,20)

odd_numbers = [number for number in numbers if number % 2 != 0]

print(odd_numbers)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


In [41]:
# SLicing Elements

In [40]:
# SLicing 1-D elements

In [32]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])

[2 3 4 5]


In [33]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[4:])

[5 6 7 8 9]


In [34]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[:4])

[1 2 3 4]


In [36]:
# Negative Slicing
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[-3:-1])

[7 8]


In [38]:
# Using step method 
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5:2])

[2 4]


In [39]:
# Returning every other element from the entire array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[::2])

[1 3 5 7 9]


In [50]:
# Slicing 2-D elements 

In [51]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [52]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [53]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [54]:
# Data Types 

In [55]:
# Checking Data Type of an Array

In [56]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype) 

<U6


In [57]:
# NUMPY Copy and View

In [58]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[42  2  3  4  5]


In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x) 

[42  2  3  4  5]
[1 2 3 4 5]


In [60]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 31

print(arr)
print(x) 

[31  2  3  4  5]
[31  2  3  4  5]


In [62]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 31

print(arr)
print(x) 

[31  2  3  4  5]
[1 2 3 4 5]


In [68]:
# Numpy shape 

In [69]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [70]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [71]:
# Numpy Reshaping

In [72]:
# Numbpy reshaping from 1-D to 2-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [73]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr) 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
